//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab08.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Staff", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Staff : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        private System.DateTime Hire_DateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Hire_Date {
            get {
                return this.Hire_DateField;
            }
            set {
                if ((this.Hire_DateField.Equals(value) != true)) {
                    this.Hire_DateField = value;
                    this.RaisePropertyChanged("Hire_Date");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name GetStaffsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStaffs", ReplyAction="*")]
        Lab08.ServiceReference1.GetStaffsResponse GetStaffs(Lab08.ServiceReference1.GetStaffsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStaffs", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab08.ServiceReference1.GetStaffsResponse> GetStaffsAsync(Lab08.ServiceReference1.GetStaffsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStaffsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStaffs", Namespace="http://tempuri.org/", Order=0)]
        public Lab08.ServiceReference1.GetStaffsRequestBody Body;
        
        public GetStaffsRequest() {
        }
        
        public GetStaffsRequest(Lab08.ServiceReference1.GetStaffsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetStaffsRequestBody {
        
        public GetStaffsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStaffsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStaffsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab08.ServiceReference1.GetStaffsResponseBody Body;
        
        public GetStaffsResponse() {
        }
        
        public GetStaffsResponse(Lab08.ServiceReference1.GetStaffsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStaffsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab08.ServiceReference1.Staff[] GetStaffsResult;
        
        public GetStaffsResponseBody() {
        }
        
        public GetStaffsResponseBody(Lab08.ServiceReference1.Staff[] GetStaffsResult) {
            this.GetStaffsResult = GetStaffsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Lab08.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Lab08.ServiceReference1.WebService1Soap>, Lab08.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab08.ServiceReference1.GetStaffsResponse Lab08.ServiceReference1.WebService1Soap.GetStaffs(Lab08.ServiceReference1.GetStaffsRequest request) {
            return base.Channel.GetStaffs(request);
        }
        
        public Lab08.ServiceReference1.Staff[] GetStaffs() {
            Lab08.ServiceReference1.GetStaffsRequest inValue = new Lab08.ServiceReference1.GetStaffsRequest();
            inValue.Body = new Lab08.ServiceReference1.GetStaffsRequestBody();
            Lab08.ServiceReference1.GetStaffsResponse retVal = ((Lab08.ServiceReference1.WebService1Soap)(this)).GetStaffs(inValue);
            return retVal.Body.GetStaffsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab08.ServiceReference1.GetStaffsResponse> Lab08.ServiceReference1.WebService1Soap.GetStaffsAsync(Lab08.ServiceReference1.GetStaffsRequest request) {
            return base.Channel.GetStaffsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab08.ServiceReference1.GetStaffsResponse> GetStaffsAsync() {
            Lab08.ServiceReference1.GetStaffsRequest inValue = new Lab08.ServiceReference1.GetStaffsRequest();
            inValue.Body = new Lab08.ServiceReference1.GetStaffsRequestBody();
            return ((Lab08.ServiceReference1.WebService1Soap)(this)).GetStaffsAsync(inValue);
        }
    }
}
