//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintForCinema
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ComplaintJobHistory
    {
        [Display(Name = "Id")]
        public System.Guid ComplaintJobHistoryID { get; set; }
        [Display(Name = "Queja/Reclamacion")]
        public System.Guid ComplaintID { get; set; }
        [Display(Name = "Descripcion")]
        public string ComplaintJobHistoryDescription { get; set; }
        [Display(Name = "Fecha")]
        public System.DateTime ComplaintJobHistoryDate { get; set; }
        [Display(Name = "Usuario")]
        public string UserID { get; set; }
    
        public virtual Complaint Complaint { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
