//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintForCinema
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Complaint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Complaint()
        {
            this.ComplaintJobHistories = new HashSet<ComplaintJobHistory>();
            this.Complaint_ComplaintDepartament = new HashSet<Complaint_ComplaintDepartament>();
            this.ComplaintUserHistories = new HashSet<ComplaintUserHistory>();
        }
        [Display(Name = "ID")]

        public System.Guid ComplaintID { get; set; }
 
        public System.Guid ComplaintTypeID { get; set; }
        [Display(Name = "Titulo")]
        public string ComplaintTitle { get; set; }
        [Display(Name = "Descripcion")]
        public string ComplaintDescription { get; set; }
        public string UserID { get; set; }
        public System.Guid ComplaintProductID { get; set; }
        [Display(Name = "Fecha")]
        public System.DateTime ComplaintDate { get; set; }
        public System.Guid ComplaintStatusID { get; set; }
        public System.Guid ComplaintLocationID { get; set; }
        [Display(Name = "Comentarios")]
        public string ComplaintCommets { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComplaintJobHistory> ComplaintJobHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Complaint_ComplaintDepartament> Complaint_ComplaintDepartament { get; set; }
        public virtual ComplaintLocation ComplaintLocation { get; set; }
        public virtual ComplaintProduct ComplaintProduct { get; set; }
        public virtual ComplaintStatu ComplaintStatu { get; set; }
        public virtual ComplaintType ComplaintType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComplaintUserHistory> ComplaintUserHistories { get; set; }
    }
}
