//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintForCinema
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ComplaintProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComplaintProduct()
        {
            this.Complaints = new HashSet<Complaint>();
        }
        [Display(Name = "Id")]
        public System.Guid ComplaintProductID { get; set; }
        [Display(Name = "Producto")]
        public string ComplaintProductDescription { get; set; }
        [Display(Name = "Categoria")]
        public System.Guid ComplaintCategoryID { get; set; }
        [Display(Name = "Estado")]
        public bool ComplaintProductIsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Complaint> Complaints { get; set; }
        public virtual ComplaintCategory ComplaintCategory { get; set; }
    }
}
