//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintForCinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplaintUserHistory
    {
        public System.Guid ComplaintUserHistoryID { get; set; }
        public System.Guid ComplaintID { get; set; }
        public string ComplaintUserHistoryDescription { get; set; }
        public System.DateTime ComplaintJobHistoryDate { get; set; }
        public string UserID { get; set; }
    
        public virtual Complaint Complaint { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
