//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintForCinema
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComplaintCinemaEntities : DbContext
    {
        public ComplaintCinemaEntities()
            : base("name=ComplaintCinemaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Complaint> Complaints { get; set; }
        public virtual DbSet<Complaint_ComplaintDepartament> Complaint_ComplaintDepartament { get; set; }
        public virtual DbSet<ComplaintCategory> ComplaintCategories { get; set; }
        public virtual DbSet<ComplaintDepartament> ComplaintDepartaments { get; set; }
        public virtual DbSet<ComplaintJobHistory> ComplaintJobHistories { get; set; }
        public virtual DbSet<ComplaintLocation> ComplaintLocations { get; set; }
        public virtual DbSet<ComplaintProduct> ComplaintProducts { get; set; }
        public virtual DbSet<ComplaintStatu> ComplaintStatus { get; set; }
        public virtual DbSet<ComplaintType> ComplaintTypes { get; set; }
        public virtual DbSet<ComplaintUserHistory> ComplaintUserHistories { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
