//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintForCinema
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Complaint_ComplaintDepartament
    {
        [Display(Name = "Id")]
        public System.Guid Complaint_ComplaintDepartamentID { get; set; }
        [Display(Name = "Departamento")]
        public System.Guid ComplaintDepartamentID { get; set; }
        [Display(Name = "Queja/Reclamacion")]
        public System.Guid ComplaintID { get; set; }
    
        public virtual Complaint Complaint { get; set; }
        public virtual ComplaintDepartament ComplaintDepartament { get; set; }
    }
}
