//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintForCinema
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ComplaintCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComplaintCategory()
        {
            this.ComplaintProducts = new HashSet<ComplaintProduct>();
        }
        [Display(Name = "Id")]
        public System.Guid ComplaintCategoryID { get; set; }
        [Display(Name = "Categoria")]
        public string ComplaintCategoryDescription { get; set; }
        [Display(Name = "Estado")]
        public Nullable<bool> ComplaintCategoryIsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComplaintProduct> ComplaintProducts { get; set; }
    }
}
